### ISSUE TITLE
apollo-modules vs. apollo-redux-tools vs apollo-mantra

### ISSUE THREAD

**Issue by smooJitter** [tomitrescak/apollo-modules#1]
Hello,

I'm curious to know do I need to install all three of these packages or are they linked to each other?

**Comment by tomitrescak** [comment]
@smooJitter 

Apollo-modules should be installed on your server. I have separated it from apollo-mantra just for this purpose. 

Apollo-mantra is aimed for the client as it brings mantra approach to apollo.

apollo-redux-tools will soon be deprecated.

**Comment by smooJitter** [comment]
@tomitrescak 

Hello, 

After looking at the TutorialHelper repo, I'm and still having a hard time setting up  this package.   I notice this is a typescript package, and TutorialHelpers repo is a typescript repo.  Does the mean qraphQL I need to user typescript in order to make of use of these packages (apolla-mantra, apollo-modules)?   I'm still getting the following error:

```
   /Users/dwaynecole/jitter/.meteor/local/build/programs/server/packages/modules.js:61985
   const { addModules, createServer  } = require('./dist/schema');
             ^           
  SyntaxError: Unexpected token { at Object.exports.runInThisContext (vm.js:53:16)
     at /Users/dwaynecole/jitter/.meteor/local/build/programs/server/boot.js:287:30
     at Array.forEach (native)
     at Function._.each._.forEach (/Users/dwaynecole/.meteor/packages/meteor-tool/.1.4.1_1.veow5w++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)

     at /Users/dwaynecole/jitter/.meteor/local/build/programs/server/boot.js:128:5

```

It appears to have something to do with package.  Note, after installing the package, I received an UNMET PEER DEPENDENCY webpack@1 || ^2.1.0-beta.  Do you think this have something to do with this?
